_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 442e6494-3a9a-477c-96b0-c37c862497c1
name: unicorninvesting.us
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /unicorn
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
