_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 9440fee4-b2b6-4a5b-9a1a-af0fbb125356
name: unicorninvesting.us
mail: Unicorninvesting@stlouisintegration.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
