"""
ETH Enhanced Technical Analysis Algorithm
========================================

Complete LEAN algorithm using the Enhanced ETH Technical Alpha model
with comprehensive 30+ indicator analysis.

This algorithm demonstrates Phase 2 implementation:
- Technical Analysis Alpha using Phase 1 validated indicators
- Real-time signal generation with confidence scoring
- Portfolio construction and risk management
- Performance monitoring and logging

Integration Points:
- IBKR Gateway data feed (Contract ID: 541686654)
- Enhanced ETH Technical Alpha model
- Dynamic position sizing based on confidence
- Comprehensive logging and monitoring
"""

from AlgorithmImports import *
from EnhancedETHTechnicalAlpha import EnhancedETHTechnicalAlpha

class ETHEnhancedTechnicalAlgorithm(QCAlgorithm):
    """
    ETH trading algorithm using enhanced technical analysis.
    
    Features:
    - 30+ technical indicators for signal generation
    - Dynamic position sizing based on signal confidence
    - Risk management with stop-loss and take-profit
    - Real-time performance monitoring
    - Comprehensive logging for analysis
    """
    
    def initialize(self):
        """Initialize the ETH Enhanced Technical Analysis Algorithm."""
        
        # Algorithm Configuration
        self.set_start_date(2024, 1, 1)
        self.set_end_date(2025, 8, 29)
        self.set_cash(100000)  # $100k starting capital
        
        # Data Resolution and Timezone
        self.set_time_zone("America/New_York")
        
        # Add ETH as primary trading asset
        self.eth_symbol = self.add_crypto("ETHUSD", Resolution.MINUTE, Market.COINBASE).symbol
        
        # Initialize Enhanced Alpha Model
        self.enhanced_alpha = EnhancedETHTechnicalAlpha(
            prediction_horizon_hours=2,
            confidence_threshold=0.02,  # 2% minimum confidence
            max_signals_per_update=1,
            enable_multi_timeframe=True
        )
        
        # Set Alpha Model
        self.set_alpha(self.enhanced_alpha)
        
        # Portfolio Construction - Equal weighting with confidence scaling
        self.set_portfolio_construction(EqualWeightingPortfolioConstructionModel(
            rebalance=Resolution.HOUR  # Rebalance hourly
        ))
        
        # Execution Model - Immediate execution
        self.set_execution(ImmediateExecutionModel())
        
        # Risk Management
        self.set_risk_management(MaximumDrawdownPercentPerSecurity(0.05))  # 5% max drawdown per security
        
        # Performance tracking
        self.performance_metrics = {
            'total_signals': 0,
            'profitable_signals': 0,
            'total_trades': 0,
            'profitable_trades': 0,
            'max_confidence': 0,
            'avg_confidence': 0,
            'last_rebalance': None
        }
        
        # Schedule performance reporting
        self.schedule.on(
            self.date_rules.every_day(self.eth_symbol),
            self.time_rules.at(23, 55),  # Daily summary at 11:55 PM
            self.daily_performance_report
        )
        
        self.debug("🚀 ETH Enhanced Technical Algorithm Initialized")
        self.debug(f"📊 Using Enhanced Alpha with Phase 1 Technical Indicators")
        self.debug(f"💰 Starting Capital: ${self.portfolio.cash:,.2f}")
    
    def on_data(self, data):
        """
        Handle incoming data and monitor algorithm performance.
        
        This method runs on every data update and provides real-time monitoring.
        """
        if not data.contains_key(self.eth_symbol):
            return
            
        # Get current market data
        current_price = data[self.eth_symbol].close
        current_volume = data[self.eth_symbol].volume
        
        # Monitor algorithm status
        if self.time.minute % 15 == 0:  # Every 15 minutes
            self._log_status_update(current_price, current_volume)
    
    def on_insights_generated(self, algorithm, insights):
        """
        Monitor insights generated by the Enhanced Alpha model.
        
        This provides real-time feedback on signal generation and quality.
        """
        for insight in insights:
            if insight.symbol == self.eth_symbol:
                self.performance_metrics['total_signals'] += 1
                
                # Update confidence metrics
                confidence = insight.confidence if hasattr(insight, 'confidence') else 0
                self.performance_metrics['max_confidence'] = max(
                    self.performance_metrics['max_confidence'], confidence
                )
                
                # Calculate running average confidence
                total_signals = self.performance_metrics['total_signals']
                current_avg = self.performance_metrics['avg_confidence']
                self.performance_metrics['avg_confidence'] = (
                    (current_avg * (total_signals - 1) + confidence) / total_signals
                )
                
                # Log insight details
                direction_emoji = "🔼" if insight.direction == InsightDirection.UP else "🔽"
                self.debug(f"{direction_emoji} ETH INSIGHT: "
                          f"Direction: {insight.direction}, "
                          f"Magnitude: {insight.magnitude:.3%}, "
                          f"Confidence: {confidence:.3f}, "
                          f"Weight: {insight.weight:.3f}")
                          
                if hasattr(insight, 'tag') and insight.tag:
                    self.debug(f"📊 Signal Details: {insight.tag}")
    
    def on_portfolio_changed(self, algorithm, changes):
        """
        Track portfolio changes and trading performance.
        """
        for security in changes.values():
            if security.symbol == self.eth_symbol:
                self.performance_metrics['total_trades'] += 1
                
                # Log position changes
                quantity = security.quantity
                if quantity != 0:
                    avg_price = security.average_price
                    market_value = security.holdings_value
                    
                    self.debug(f"💼 ETH POSITION UPDATE: "
                              f"Quantity: {quantity:.4f}, "
                              f"Avg Price: ${avg_price:,.2f}, "
                              f"Market Value: ${market_value:,.2f}")
    
    def on_order_event(self, order_event):
        """
        Monitor order execution and trading activity.
        """
        if order_event.symbol == self.eth_symbol:
            order = self.transactions.get_order_by_id(order_event.order_id)
            
            if order_event.status == OrderStatus.FILLED:
                fill_price = order_event.fill_price
                fill_quantity = order_event.fill_quantity
                
                action = "BUY" if fill_quantity > 0 else "SELL"
                action_emoji = "🟢" if action == "BUY" else "🔴"
                
                self.debug(f"{action_emoji} ETH ORDER FILLED: "
                          f"{action} {abs(fill_quantity):.4f} ETH @ ${fill_price:,.2f}")
                          
                # Update trade statistics
                if order.tag and "insight" in order.tag.lower():
                    # This was generated by our alpha model
                    self._update_trade_performance(order_event)
    
    def daily_performance_report(self):
        """
        Generate daily performance summary.
        """
        portfolio_value = self.portfolio.total_portfolio_value
        unrealized_profit = self.portfolio.total_unrealized_profit
        portfolio_return = (portfolio_value / self.portfolio.total_holdings_cost - 1) * 100
        
        # ETH-specific metrics
        eth_holdings = self.portfolio[self.eth_symbol]
        eth_quantity = eth_holdings.quantity
        eth_value = eth_holdings.holdings_value
        eth_profit = eth_holdings.unrealized_profit
        
        # Alpha model status
        alpha_status = self.enhanced_alpha.get_status_summary()
        
        self.debug("📈 DAILY PERFORMANCE REPORT")
        self.debug("=" * 50)
        self.debug(f"📅 Date: {self.time.strftime('%Y-%m-%d')}")
        self.debug(f"💰 Portfolio Value: ${portfolio_value:,.2f}")
        self.debug(f"📊 Portfolio Return: {portfolio_return:+.2f}%")
        self.debug(f"💵 Unrealized P&L: ${unrealized_profit:+,.2f}")
        self.debug("")
        self.debug(f"🪙 ETH Position: {eth_quantity:.4f} ETH")
        self.debug(f"💎 ETH Value: ${eth_value:,.2f}")
        self.debug(f"📈 ETH P&L: ${eth_profit:+,.2f}")
        self.debug("")
        self.debug(f"🎯 Total Signals: {self.performance_metrics['total_signals']}")
        self.debug(f"📊 Avg Confidence: {self.performance_metrics['avg_confidence']:.3f}")
        self.debug(f"🏆 Max Confidence: {self.performance_metrics['max_confidence']:.3f}")
        self.debug(f"💼 Total Trades: {self.performance_metrics['total_trades']}")
        self.debug("")
        self.debug(f"🔧 Alpha Status: {alpha_status['model_type']}")
        self.debug(f"📡 Indicators Available: {alpha_status['indicators_available']}")
        self.debug("=" * 50)
    
    def _log_status_update(self, current_price, current_volume):
        """Log periodic status updates."""
        portfolio_value = self.portfolio.total_portfolio_value
        cash_percent = (self.portfolio.cash / portfolio_value) * 100
        
        self.debug(f"⏰ STATUS ({self.time.strftime('%H:%M')}): "
                  f"ETH ${current_price:,.2f}, "
                  f"Portfolio ${portfolio_value:,.0f}, "
                  f"Cash {cash_percent:.1f}%")
    
    def _update_trade_performance(self, order_event):
        """Update trading performance metrics."""
        # Simplified performance tracking
        # In a real implementation, you would track entry/exit pairs
        # and calculate profit/loss for each complete trade
        
        if order_event.fill_quantity < 0:  # Sell order
            # Check if this was profitable (simplified)
            current_holdings = self.portfolio[self.eth_symbol]
            if current_holdings.unrealized_profit > 0:
                self.performance_metrics['profitable_trades'] += 1
    
    def on_end_of_algorithm(self):
        """
        Final performance summary when algorithm completes.
        """
        final_value = self.portfolio.total_portfolio_value
        initial_value = self.portfolio.total_holdings_cost
        total_return = (final_value / initial_value - 1) * 100
        
        self.debug("🏁 ALGORITHM COMPLETED")
        self.debug("=" * 60)
        self.debug(f"💰 Final Portfolio Value: ${final_value:,.2f}")
        self.debug(f"📈 Total Return: {total_return:+.2f}%")
        self.debug(f"🎯 Total Signals Generated: {self.performance_metrics['total_signals']}")
        self.debug(f"💼 Total Trades Executed: {self.performance_metrics['total_trades']}")
        self.debug(f"🏆 Average Signal Confidence: {self.performance_metrics['avg_confidence']:.3f}")
        self.debug("=" * 60)
        
        # Final alpha model summary
        alpha_status = self.enhanced_alpha.get_status_summary()
        self.debug(f"🔧 Final Alpha Status: {alpha_status}")
